### ISSUE TITLE
 Datatype for argument sendtype is a null datatype

### ISSUE THREAD

**Issue by CunyangWei** [variemai/mpisee#1]
I try to use mpisee with Berkeley-GW 4.0. However, I got this.

MPICH ERROR [Rank 37] [job id 32638235.0] [Wed Nov  6 18:00:41 2024] [nid008504] - Abort(269032451) (rank 37 in comm 0): Fatal error in PMPI_Allgather: Invalid datatype, error stack:
PMPI_Allgather(420): MPI_Allgather(sbuf=0xc32e44, scount=0, MPI_DATATYPE_NULL, rbuf=0x236b090, rcount=64, datatype=MPI_BYTE, comm=MPI_COMM_WORLD) failed
PMPI_Allgather(370): Datatype for argument sendtype is a null datatype

aborting job:
Fatal error in PMPI_Allgather: Invalid datatype, error stack:
PMPI_Allgather(420): MPI_Allgather(sbuf=0xc32e44, scount=0, MPI_DATATYPE_NULL, rbuf=0x236b090, rcount=64, datatype=MPI_BYTE, comm=MPI_COMM_WORLD) failed
PMPI_Allgather(370): Datatype for argument sendtype is a null datatype

Also, mpiP has the same error. Do you have any advice or experience about this?

**Comment by iovardas** [comment]
Hello, first, I want to thank you for using mpisee.  Would you please send me exactly the code and input that you are trying to run? Also does the application run normally without profiling?

**Comment by CunyangWei** [comment]
Hey, I think Mpisee is very easy to use. 

I currently test [BerkeleyGW-4.0](https://berkeleygw.org/download/) in Perlmutter (A100 supercomputer). [Here](https://gitlab.com/NERSC/N10-benchmarks/berkeleygw-workflow) is install step (only difference is I use version 4.0). I am running on "epsilon" phase with "medium" size. 

Application can run normally without profiling. Since I can normally use mpiP and mpisee with other applications, I think this issue might because Berkeley-GW use some special "MPI code" ?

Main job script is like this:
```
module purge

module load PrgEnv-gnu
module swap PrgEnv-gnu PrgEnv-nvhpc
module load cray-hdf5-parallel
module load cray-fftw
module load cray-libsci
module load python
module load cudatoolkit
module load craype-accel-nvidia80
export CRAY_ACCEL_TARGET=nvidia80
export MPICH_GPU_SUPPORT_ENABLED=1


source ../site_path_config.sh

mkdir BGW_EPSILON_$SLURM_JOBID
stripe_large BGW_EPSILON_$SLURM_JOBID
cd    BGW_EPSILON_$SLURM_JOBID
ln -s $BGW_DIR/epsilon.cplx.x .
ln -s  ../epsilon.inp .
ln -sfn  ${Si510_WFN_folder}/WFNq.h5      .
ln -sfn  ${Si510_WFN_folder}/WFN_out.h5   ./WFN.h5


ulimit -s unlimited
export OMP_PROC_BIND=true
export OMP_PLACES=threads
export HDF5_USE_FILE_LOCKING=FALSE
export BGW_HDF5_WRITE_REDIST=1
export BGW_WFN_HDF5_INDEPENDENT=1

export LD_PRELOAD=/pscratch/sd/c/cunyang/software/lib/libmpisee.so                                                  
 
export MPISEE_OUTFILE=/pscratch/sd/c/cunyang/software/mpisee_profile_${SLURM_JOB_ID}.db
export OMP_NUM_THREADS=16
srun -n 64 -c 32  --cpu-bind=cores ./epsilon.cplx.x &> out_${SLURM_JOB_ID}_$(date +"%Y-%m-%d_%H-%M-%S").txt
```

**Comment by iovardas** [comment]
Ok. I see that there are those calls within   .`/Epsilon/epsilon_main.f90`

```
    call MPI_Allgather(MPI_IN_PLACE, 0, MPI_DATATYPE_NULL, scal%imyrowd, &
      size(scal%imyrowd,1), MPI_INTEGER, MPI_COMM_WORLD, mpierr)
    call MPI_Allgather(MPI_IN_PLACE, 0, MPI_DATATYPE_NULL, scal%imycold, &
      size(scal%imycold,1), MPI_INTEGER, MPI_COMM_WORLD, mpierr)
```

Now the MPI standard allows this behavior (Section 6.7): The “in place” option for intra-communicators is specified by passing the value MPI_IN_PLACE to the argument sendbuf at all MPI processes. sendcount and sendtype are ignored.

So I have to make sure that I handle this correctly within mpisee and I will update you.

**Comment by CunyangWei** [comment]
Thank you so much!  Looking forward to your updates!

**Comment by iovardas** [comment]
This issue has been fixed in mpisee. Please see the **Updated** Readme to update and build mpisee. I would appreciate it if you provided some feedback from the Berkeley-GW runs. It would also help if you checked for correctness: Run the code without mpisee, and make sure (if possible) that the results are the same when running with mpisee.

**Comment by CunyangWei** [comment]
Now mpisee works well with Berkeley-GW and the result is correct. In the `medium` size, `Epsilon` phase, mpisee has only 4% overhead. Thank you very much for the updates!
